### ISSUE TITLE
代码结构要是能清楚点就好了 

### ISSUE THREAD

**Issue by wjwjwjwjwjwj** [zhangbin1010/acp-admin#18]
我觉得有点乱啊

**Comment by zhangbin1010** [comment]
- 工程文件结构请参看[readme](https://github.com/zhangbin1010/acp-admin#%E5%9B%9B%E5%BC%80%E5%8F%91)第四章
- 代码结构均是使用vuejs
- 哪写的不好欢迎交流，我邮箱 zhangbin1010@qq.com
